# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  veracodeAppProfile: AzDevOps.$(Build.DefinitionName)
  caminhoPacote: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: 
    steps:
    - task: GoTool@0
      inputs:
        version: '1.12'
      displayName: 'Go Install'

    - task: GoTool@0
      inputs:
        version: '1.12'
      displayName: 'Go Install'

    - script: |
        ls
        go get all
        go mod download
        go mod vendor
      displayName: 'Go Build'
      
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Agent.BuildDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(caminhoPacote)'
        replaceExistingArchive: true
      displayName: 'Criando pacote para analise'

- stage: TimeA
  displayName: TimeA
  dependsOn: Build
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        export SRCCLR_SCM_NAME=$(veracodeAppProfile)
        curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan --update-advisor --allow-dirty
    displayName: 'Veracode SCA'
    continueOnError: true
    
  - task: Veracode@3
    inputs:
      ConnectionDetailsSelection: 'Endpoint'
      AnalysisService: 'Veracode'
      veracodeAppProfile: '$(veracodeAppProfile)'
      version: '$(build.buildNumber)'
      filepath: '$(caminhoPacote)'
      sandboxName: '$(System.StageDisplayName)'
      createSandBox: true
      createProfile: true
      importResults: true
      maximumWaitTime: '360'
    displayName: 'Veracode SAST'

  - task: Veracode Flaw Importer@3
    inputs:
      ConnectionDetailsSelection: 'Endpoint'
      AnalysisService: 'Veracode'
      veracodeAppProfile: '$(veracodeAppProfile)'
      sandboxName: '$(System.StageDisplayName)'
      importType: 'All Unmitigated Flaws Violating Policy'
      workItemType: 'Issue'
      area: '$(system.teamProject)'
      addCustomTag: '$(System.StageDisplayName)'
      flawImportLimit: '1000'
    displayName: 'Veracode importando falhas'
